# Generated by Django 5.0.6 on 2024-06-01 01:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("order", "0002_alter_cartitem_product"),
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductVariants",
            new_name="ProductVariant",
        ),
    ]
