# Generated by Django 5.0.6 on 2024-06-01 15:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_image_productvariant_image_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="gender",
            field=models.CharField(
                choices=[
                    ("Male", "Male"),
                    ("Female", "Female"),
                    ("Unisex", "Unisex"),
                    ("Kid", "Kid"),
                ],
                default="Unisex",
                max_length=10,
            ),
        ),
    ]
