# Generated by Django 5.0.6 on 2024-06-20 15:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_category_category_slug_alter_image_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='product',
        ),
    ]
