# Generated by Django 5.0.6 on 2024-06-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0013_remove_order_address_order_shipping_address1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='shipping_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
